export const tableData = [
  {
    "Operation Code": "STL25-0000101",
    "Sequence Code": "40LNKRLBATT21",
    "Sequence Detail": "SHOULDER SEAM STITCH",
    Hindi: "कंधे की सिलाई",
    Tamil: "தோளின் தையல்",
    "Medicine Code": "FLCS",
    "Master Operation": "SHOULDER BINDING",
    "Skill Grade": "A",
    SMV: "2.67",
    Comments: "Initial operation",
    // sysId:"STL25-00000171"
  },
  {
    "Operation Code": "STL25-0000102",
    "Sequence Code": "40LNKRLBATT22",
    "Sequence Detail": "SLEEVE ATTACHMENT",
    Hindi: "आस्तीन जोड़ना",
    Tamil: "ஆரையால் இணைத்தல்",
    "Medicine Code": "FLCS",
    "Master Operation": "SLEEVE BINDING",
    "Skill Grade": "B",
    SMV: "0.67",
    Comments: "Check alignment",
    //  sysId:"STL25-00000172"
  },
  {
    "Operation Code": "STL25-0000103",
    "Sequence Code": "40LNKRLBATT23",
    "Sequence Detail": "COLLAR STITCH",
    Hindi: "कॉलर सिलाई",
    Tamil: "காலர் தையல்",
    "Medicine Code": "FLCS",
    "Master Operation": "COLLAR BINDING",
    "Skill Grade": "C",
    SMV: "7.60",
    Comments: "Requires precision",
    //  sysId:"STL25-00000173"
  },
  {
    "Operation Code": "STL25-0000104",
    "Sequence Code": "40LNKRLBATT24",
    "Sequence Detail": "HEM FINISHING",
    Hindi: "किनारा पूरा करना",
    Tamil: "குடை முடித்தல்",
    "Medicine Code": "FLCS",
    "Master Operation": "HEM BINDING",
    "Skill Grade": "B",
    SMV: "0.89",
    Comments: "Smooth finish required",
    //  sysId:"STL25-00000174"
  },
  {
    "Operation Code": "STL25-0000105",
    "Sequence Code": "40LNKRLBATT25",
    "Sequence Detail": "BUTTON ATTACHMENT",
    Hindi: "बटन जोड़ना",
    Tamil: "பட்டன் இணைத்தல்",
    "Medicine Code": "FLCS",
    "Master Operation": "BUTTON BINDING",
    "Skill Grade": "A",
    SMV: "1.23",
    Comments: "Use correct thread",
    //  sysId:"STL25-00000175"
  },
  {
    "Operation Code": "STL25-0000106",
    "Sequence Code": "40LNKRLBATT26",
    "Sequence Detail": "ZIPPER INSTALLATION",
    Hindi: "ज़िप जोड़ना",
    Tamil: "ஜிப்பர் இணைத்தல்",
    "Medicine Code": "FLCS",
    "Master Operation": "ZIPPER BINDING",
    "Skill Grade": "B",
    SMV: "3.89",
    Comments: "Check zipper alignment",
    //  sysId:"STL25-00000176"
  },
  {
    "Operation Code": "STL25-0000107",
    "Sequence Code": "40LNKRLBATT27",
    "Sequence Detail": "POCKET ATTACHMENT",
    Hindi: "पॉकेट जोड़ना",
    Tamil: "பாக்கெட் இணைத்தல்",
    "Medicine Code": "FLCS",
    "Master Operation": "POCKET BINDING",
    "Skill Grade": "C",
    SMV: "1.78",
    Comments: "Ensure symmetry",
    //  sysId:"STL25-00000177"
  },
  {
    "Operation Code": "STL25-0000108",
    "Sequence Code": "40LNKRLBATT28",
    "Sequence Detail": "NECK LINING STITCH",
    Hindi: "गर्दन की लाइनिंग सिलाई",
    Tamil: "கழுத்தின் வரிசை தையல்",
    "Medicine Code": "FLCS",
    "Master Operation": "NECK BINDING",
    "Skill Grade": "A",
    SMV: "1.89",
    Comments: "Neat finishing",
    //  sysId:"STL25-00000178"
  },
  {
    "Operation Code": "STL25-0000109",
    "Sequence Code": "40LNKRLBATT29",
    "Sequence Detail": "CUFF FINISHING",
    Hindi: "कफ़ पूरा करना",
    Tamil: "கஃப் முடித்தல்",
    "Medicine Code": "FLCS",
    "Master Operation": "CUFF BINDING",
    "Skill Grade": "B",
    SMV: "2.78",
    Comments: "Attention to detail",
    //  sysId:"STL25-00000179"
  },
  {
    "Operation Code": "STL25-0000110",
    "Sequence Code": "40LNKRLBATT30",
    "Sequence Detail": "LABEL ATTACHMENT",
    Hindi: "लेबल जोड़ना",
    Tamil: "லேபிள் இணைத்தல்",
    "Medicine Code": "FLCS",
    "Master Operation": "LABEL BINDING",
    "Skill Grade": "C",
    SMV: "0.32",
    Comments: "Final check",
    //  sysId:"STL25-00000180"
  },
];

import {
  Users,
  Settings,
  Building,
  Layers,
  ClipboardCheck,
  FileText,
  FileSpreadsheet,
  FileChartColumn,
  FileSearch,
  Archive,
  BookCheck,
  BookUser,
  Barcode,
  Boxes,
  Factory,
  ClipboardList,
  ClipboardSignature,
  ListChecks,
  NotebookText,
  Scissors,
  Map,
  Workflow,
  QrCode,
  Fingerprint,
  BarChart3,
  Upload,
  FileEdit,
  CalendarDays,
  Clock4,
  TimerOff,
} from "lucide-react";

export const textileColumns = [
  { key: "product", label: "Product" },
  { key: "stage", label: "Stage" },
  { key: "qty", label: "Qty (Meters)" },
];
export const textileData = [
  { product: "Cotton Fabric", stage: "Weaving", qty: "500" },
  { product: "Silk Fabric", stage: "Dyeing", qty: "200" },
  { product: "Polyester Fabric", stage: "Finishing", qty: "350" },
  { product: "Wool Fabric", stage: "Weaving", qty: "150" },
  { product: "Linen Fabric", stage: "Dyeing", qty: "400" },
  { product: "Cotton Fabric", stage: "Finishing", qty: "300" },
  { product: "Silk Fabric", stage: "Weaving", qty: "250" },
  { product: "Polyester Fabric", stage: "Dyeing", qty: "450" },
  { product: "Wool Fabric", stage: "Finishing", qty: "120" },
  { product: "Linen Fabric", stage: "Weaving", qty: "350" },
  { product: "Cotton Fabric", stage: "Dyeing", qty: "600" },
  { product: "Silk Fabric", stage: "Finishing", qty: "180" },
  { product: "Polyester Fabric", stage: "Weaving", qty: "500" },
  { product: "Wool Fabric", stage: "Dyeing", qty: "220" },
  { product: "Linen Fabric", stage: "Finishing", qty: "300" },
  { product: "Cotton Fabric", stage: "Weaving", qty: "700" },
  { product: "Silk Fabric", stage: "Dyeing", qty: "320" },
  { product: "Polyester Fabric", stage: "Finishing", qty: "480" },
  { product: "Wool Fabric", stage: "Weaving", qty: "200" },
  { product: "Linen Fabric", stage: "Dyeing", qty: "400" },
  { product: "Cotton Fabric", stage: "Finishing", qty: "550" },
  { product: "Silk Fabric", stage: "Weaving", qty: "270" },
  { product: "Polyester Fabric", stage: "Dyeing", qty: "390" },
  { product: "Wool Fabric", stage: "Finishing", qty: "160" },
  { product: "Linen Fabric", stage: "Weaving", qty: "430" },
];
export const columns = [
  { key: "product", label: "Product" },
  { key: "quantity", label: "Quantity" },
  { key: "unit", label: "Unit" },
  { key: "price", label: "Price" },
  { key: "orderDate", label: "Order date" },
  { key: "deliveryDate", label: "Delivery date" },
  { key: "status", label: "Status" },
];

export const data = [
  {
    product: "Cotton Fabric",
    quantity: 500,
    unit: "Meters",
    price: "25000",
    orderDate: "2025-11-18",
    deliveryDate: "2025-11-25",
    status: "Pending",
  },
  {
    product: "Silk Saree Roll",
    quantity: 120,
    unit: "Meters",
    price: "48000",
    orderDate: "2025-11-17",
    deliveryDate: "2025-11-26",
    status: "Completed",
  },
  {
    product: "Polyester Yarn",
    quantity: 300,
    unit: "Kg",
    price: "15000",
    orderDate: "2025-11-16",
    deliveryDate: "2025-11-23",
    status: "In Progress",
  },
  {
    product: "Denim Fabric",
    quantity: 250,
    unit: "Meters",
    price: "32500",
    orderDate: "2025-11-15",
    deliveryDate: "2025-11-27",
    status: "Cancelled",
  },
  {
    product: "Woolen Yarn",
    quantity: 180,
    unit: "Kg",
    price: "54000",
    orderDate: "2025-11-13",
    deliveryDate: "2025-11-22",
    status: "Completed",
  },
  {
    product: "Linen Fabric",
    quantity: 350,
    unit: "Meters",
    price: "45500",
    orderDate: "2025-11-12",
    deliveryDate: "2025-11-21",
    status: "In Progress",
  },
  {
    product: "cotton",
    quantity: 320,
    unit: "Meters",
    price: "45500",
    orderDate: "2025-02-30",
    deliveryDate: "2025-09-25",
    status: "Pending",
  },
  {
    product: "Fabric",
    quantity: 50,
    unit: "Meters",
    price: "45500",
    orderDate: "2025-07-2",
    deliveryDate: "2025-10-01",
    status: "Cancelled",
  },
  {
    product: "Linen Fabric",
    quantity: 350,
    unit: "Meters",
    price: "45500",
    orderDate: "2025-11-12",
    deliveryDate: "2025-11-21",
    status: "In Progress",
  },
  {
    product: "Denim Fabric",
    quantity: 250,
    unit: "Meters",
    price: "32500",
    orderDate: "2025-11-15",
    deliveryDate: "2025-11-27",
    status: "Cancelled",
  },
];

export const PurchaseHeader = [
  { key: "id", label: "Id" },
  { key: "product", label: "Product" },
  { key: "stage", label: "Stage" },
  { key: "qty", label: "Qty (Meters)" },
  { key: "unit", label: "Unit" },
  { key: "price", label: "Price" },
  { key: "orderDate", label: "Order date" },
  { key: "deliveryDate", label: "Delivery date" },
  { key: "status", label: "Status" },
];

export const PurchaseDataColumn = [
  {
    id: "PID001",
    product: "Cotton Fabric",
    stage: "Weaving",
    qty: "500",
    unit: "Meters",
    price: "32500",
    orderDate: "2025-11-15",
    deliveryDate: "2025-11-27",
    status: "Cancelled",
  },
  {
    id: "PID002",
    product: "Polyester Yarn",
    stage: "Spinning",
    qty: "800",
    unit: "Kg",
    price: "52000",
    orderDate: "2025-10-05",
    deliveryDate: "2025-10-20",
    status: "Delivered",
  },
  {
    id: "PID002",
    product: "Lycra Fabric",
    stage: "Knitting",
    qty: "300",
    unit: "Meters",
    price: "28000",
    orderDate: "2025-09-12",
    deliveryDate: "2025-09-25",
    status: "Pending",
  },
  {
    id: "PID003",
    product: "Viscose Yarn",
    stage: "Dyeing",
    qty: "1200",
    unit: "Kg",
    price: "90000",
    orderDate: "2025-11-01",
    deliveryDate: "2025-11-18",
    status: "In Progress",
  },
  {
    id: "PID004",
    product: "Denim Fabric",
    stage: "Finishing",
    qty: "700",
    unit: "Meters",
    price: "45000",
    orderDate: "2025-07-25",
    deliveryDate: "2025-08-10",
    status: "Delivered",
  },
  {
    id: "PID005",
    product: "Silk Thread",
    stage: "Spinning",
    qty: "200",
    unit: "Kg",
    price: "75000",
    orderDate: "2025-06-15",
    deliveryDate: "2025-06-30",
    status: "Cancelled",
  },
  {
    id: "PID006",
    product: "Nylon Fabric",
    stage: "Weaving",
    qty: "950",
    unit: "Meters",
    price: "61000",
    orderDate: "2025-05-05",
    deliveryDate: "2025-05-22",
    status: "Pending",
  },
  {
    id: "PID007",
    product: "Cotton Yarn",
    stage: "Spinning",
    qty: "1600",
    unit: "Kg",
    price: "120000",
    orderDate: "2025-04-18",
    deliveryDate: "2025-05-04",
    status: "Delivered",
  },
  {
    id: "PID008",
    product: "Rayon Fabric",
    stage: "Knitting",
    qty: "450",
    unit: "Meters",
    price: "33000",
    orderDate: "2025-08-01",
    deliveryDate: "2025-08-15",
    status: "In Progress",
  },
  {
    id: "PID009",
    product: "Fleece Fabric",
    stage: "Finishing",
    qty: "600",
    unit: "Meters",
    price: "56000",
    orderDate: "2025-10-12",
    deliveryDate: "2025-10-30",
    status: "Delivered",
  },
  {
    id: "PID010",
    product: "Cotton Grey Fabric",
    stage: "Weaving",
    qty: "1100",
    unit: "Meters",
    price: "70000",
    orderDate: "2025-09-20",
    deliveryDate: "2025-10-02",
    status: "Pending",
  },
  {
    id: "PID011",
    product: "Polyester Yarn",
    stage: "Spinning",
    qty: "800",
    unit: "Kg",
    price: "52000",
    orderDate: "2025-10-05",
    deliveryDate: "2025-10-20",
    status: "Delivered",
  },
];

export const qualityModules = [
  {
    title: "AQL Forms",
    icon: ClipboardCheck,
    color: "bg-blue-100 text-blue-700",
  },

  {
    title: "All Quality Check Form",
    icon: ListChecks,
    color: "bg-green-100 text-green-700",
  },

  {
    title: "Quality Reports",
    icon: FileText,
    color: "bg-yellow-100 text-yellow-700",
  },

  {
    title: "Fabric Inspection Forms",
    icon: FileSpreadsheet,
    color: "bg-sky-100 text-sky-700",
  },

  {
    title: "Fabric Inspection Report",
    icon: FileText,
    color: "bg-teal-100 text-teal-700",
  },

  {
    title: "Fabric Inspection Entry Report",
    icon: FileChartColumn,
    color: "bg-rose-100 text-rose-700",
  },

  { title: "Rework", icon: Settings, color: "bg-orange-100 text-orange-700" },

  {
    title: "Mills Fabric Parameter Forms & Reports",
    icon: Factory,
    color: "bg-indigo-100 text-indigo-700",
  },

  {
    title: "Fabric Inspection Miles/Suppiler",
    icon: Building,
    color: "bg-cyan-100 text-cyan-700",
  },

  {
    title: "EDI Fabric Inspection Forms",
    icon: FileSearch,
    color: "bg-emerald-100 text-emerald-700",
  },

  {
    title: "Fabric Inspection Comparison Report",
    icon: FileChartColumn,
    color: "bg-violet-100 text-violet-700",
  },

  {
    title: "Needle Received Stock",
    icon: Boxes,
    color: "bg-amber-100 text-amber-700",
  },

  {
    title: "Needle Controlled Log",
    icon: NotebookText,
    color: "bg-red-100 text-red-700",
  },

  {
    title: "IDLE Needle Issue/Recieve Details",
    icon: ClipboardList,
    color: "bg-lime-100 text-lime-700",
  },

  {
    title: "Needle Reports",
    icon: FileText,
    color: "bg-slate-100 text-slate-700",
  },

  {
    title: "Needle Reports View",
    icon: FileText,
    color: "bg-fuchsia-100 text-fuchsia-700",
  },

  {
    title: "Fabric Inspection Adishtam",
    icon: ClipboardSignature,
    color: "bg-blue-100 text-blue-700",
  },

  {
    title: "Adhistam Fabric Inspection Report",
    icon: FileText,
    color: "bg-teal-100 text-teal-700",
  },

  {
    title: "Inline Quality Audit Report",
    icon: ClipboardCheck,
    color: "bg-green-100 text-green-700",
  },

  {
    title: "Fabric Lab Inspection",
    icon: BookUser,
    color: "bg-rose-100 text-rose-700",
  },
];

export const cuttingModules = [
  { title: "OPSEQ", icon: Workflow, color: "bg-indigo-100 text-indigo-700" },

  {
    title: "Operation Mapping",
    icon: Map,
    color: "bg-green-100 text-green-700",
  },

  {
    title: "Bundle Operation",
    icon: Scissors,
    color: "bg-rose-100 text-rose-700",
  },

  {
    title: "QR Code Building Reports",
    icon: QrCode,
    color: "bg-yellow-100 text-yellow-700",
  },

  {
    title: "Cut Panel Bundle Audit",
    icon: ClipboardCheck,
    color: "bg-purple-100 text-purple-700",
  },

  {
    title: "Style System Id Tracking",
    icon: Fingerprint,
    color: "bg-cyan-100 text-cyan-700",
  },

  {
    title: "Daily Cutting CPI",
    icon: BarChart3,
    color: "bg-blue-100 text-blue-700",
  },

  {
    title: "CPI QR Code Building Report",
    icon: FileChartColumn,
    color: "bg-orange-100 text-orange-700",
  },

  {
    title: "Print & Embroidery QR Gen Reports",
    icon: QrCode,
    color: "bg-emerald-100 text-emerald-700",
  },

  {
    title: "Print & Embroidery CPI QR Gen Uploader",
    icon: Upload,
    color: "bg-red-100 text-red-700",
  },

  {
    title: "Print & Embroidery CPI QR Gen Reports",
    icon: FileSearch,
    color: "bg-teal-100 text-teal-700",
  },

  {
    title: "Cutting Panel Audit Report",
    icon: ClipboardList,
    color: "bg-amber-100 text-amber-700",
  },

  {
    title: "QC Rework Operation QR",
    icon: ClipboardSignature,
    color: "bg-slate-100 text-slate-700",
  },
];
export const iEDepartmentModules = [
  {
    title: "System Operation",
    icon: Settings,
    color: "bg-indigo-100 text-indigo-700",
  },
  {
    title: "Operation Master",
    icon: ListChecks,
    color: "bg-green-100 text-green-700",
  },
  {
    title: "Operation Report and Modification",
    icon: FileEdit,
    color: "bg-rose-100 text-rose-700",
  },
  {
    title: "Daily ForeCast Report",
    icon: CalendarDays,
    color: "bg-yellow-100 text-yellow-700",
  },
  {
    title: "Operator wise Hourly Production Reports",
    icon: Clock4,
    color: "bg-orange-100 text-orange-700",
  },
  {
    title: "QR Operation Reports",
    icon: QrCode,
    color: "bg-purple-100 text-purple-700",
  },
  {
    title: "ForeCast Order",
    icon: ClipboardList,
    color: "bg-teal-100 text-teal-700",
  },
  {
    title: "ManPower Lost Time",
    icon: TimerOff,
    color: "bg-red-100 text-red-700",
  },
];

export const cards = [
  { title: "Quality Modules", modules: qualityModules },
  { title: "IE Department", modules: iEDepartmentModules },
  { title: "Cutting Modules", modules: cuttingModules },
  { title: "Style Operation", modules: iEDepartmentModules },
  //    { title: "Rework", modules: cuttingModules },
  //    { title: "Fabric Modules", modules: qualityModules },
];


export const productionList = [
  {
    date: "07/11/2025",
    lineNo: "06",
    styleNo: "AOP SleepSuit - BRAND",
    operation: "BACK NECK ATTACH",
    sequence: 0,
    totalQty: 21,
  },
  {
    date: "07/11/2025",
    lineNo: "02",
    styleNo: "KIDS CHARCOAL PANT",
    operation: "HEAT SEAL",
    sequence: 1,
    totalQty: 30,
  },
  {
    date: "07/11/2025",
    lineNo: "06",
    styleNo: "KIDS CHARCOAL PANT",
    operation: "HEAT SEAL",
    sequence: 1,
    totalQty: 86,
  },
  {
    date: "07/11/2025",
    lineNo: "01",
    styleNo: "AOP SleepSuit - BRAND",
    operation: "BINDING CUT",
    sequence: 3,
    totalQty: 42,
  },
  {
    date: "07/11/2025",
    lineNo: "06",
    styleNo: "Dixcy Sure Shorts 04",
    operation: "ZIPPER STOPPER TACK",
    sequence: 3,
    totalQty: 250,
  },
  {
    date: "07/11/2025",
    lineNo: "01",
    styleNo: "AOP SleepSuit - BRAND",
    operation: "NECK BINDING",
    sequence: 4,
    totalQty: 42,
  },
  {
    date: "07/11/2025",
    lineNo: "06",
    styleNo: "Dixcy Sure Shorts 04",
    operation: "SIDE LABEL TACK",
    sequence: 4,
    totalQty: 204,
  },
  {
    date: "07/11/2025",
    lineNo: "01",
    styleNo: "AOP SleepSuit - BRAND",
    operation: "FACING OVERLOCK",
    sequence: 5,
    totalQty: 22,
  },
  {
    date: "07/11/2025",
    lineNo: "05",
    styleNo: "Body Suit",
    operation: "BOTTOM BINDING FRONT AND BACK",
    sequence: 5,
    totalQty: 44,
  },
  {
    date: "07/11/2025",
    lineNo: "06",
    styleNo: "Dixcy Sure Shorts 04",
    operation: "MARK POCKET",
    sequence: 5,
    totalQty: 60,
  },
  {
    date: "07/11/2025",
    lineNo: "01",
    styleNo: "AOP SleepSuit - BRAND",
    operation: "ZIPPER TACK WITH FACING OVERLOCK",
    sequence: 6,
    totalQty: 87,
  },
  {
    date: "07/11/2025",
    lineNo: "02",
    styleNo: "Body Suit",
    operation: "SLEEVE ATTACH",
    sequence: 6,
    totalQty: 88,
  },
  {
    date: "07/11/2025",
    lineNo: "06",
    styleNo: "Dixcy Sure Shorts 04",
    operation: "POCKET EDGE OL",
    sequence: 6,
    totalQty: 450,
  },
  {
    date: "07/11/2025",
    lineNo: "02",
    styleNo: "Body Suit",
    operation: "SEW SIDE SEAM BOTH SIDE",
    sequence: 7,
    totalQty: 44,
  },
];


export const qrData = [
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
  },
  {
   style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
  },
  {
     style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 23,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 22,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 21,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 20,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 19,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 18,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 17,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 16,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 15,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 14,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 13,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 12,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 11,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 10,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 11,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 10,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 9,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 8,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 7,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 6,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 5,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
   {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "6-9M",
    bundle: "5912",
    qty: "21",
    serial: 4,
    tamil: "பெட்டி",
    hindi: "पैकिंग",
    ratio: "42/61/84",
  },
  {
    style: "AOP SleepSuit-NON BRAND",
    item: "324",
    layer: "L-01-6100",
    color: "City AOP on White",
    size: "9-12M",
    bundle: "5913",
    qty: "22",
    serial: 3,
    tamil: "ஜிப்பர் இணைப்பு",
    hindi: "जिपर अटैच",
    ratio: "50/72/99",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 2,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
  {
    style: "KIDS BASIC TEE",
    item: "255",
    layer: "L-02-5021",
    color: "Red",
    size: "12-18M",
    bundle: "6001",
    qty: "18",
    serial: 1,
    tamil: "கால் இணைப்பு",
    hindi: "पैर जोड़",
    ratio: "39/57/78",
  },
];